name: 2.1.$(devops_buildNumber)

pr:
  branches:
    include:
    - master
    - dev
    - v3.x

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format(''), 1500)]

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: OneLocBuild@2
  enabled: false
  inputs:
    locProj: 'Build\Localize\LocProject.json'
    outDir: '$(Build.Repository.LocalPath)'
    packageSourceAuth: 'patAuth'
    patVariable: '$(ONELOCBUILD)'
    continueOnError: true
- task: CopyFiles@2
  enabled: false
  displayName: 'Copy Loc files to publish directories'
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)/loc
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  enabled: false
  displayName: 'Publish Artifact: loc'
  inputs:
    ArtifactName: 'loc'
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.\Build'
  
- task: Gulp@1
  inputs:
    buildNumber: $(devops_buildNumber)
    gulpFile: '.\Build\gulpfile.js'
    targets: 'build-all'
    enableCodeCoverage: false

- task: PowerShell@2
  inputs:
    commitId: $(Build.SourceVersion)
    filePath: '.\Build\scripts\uploadVersionInfoToStorage.ps1'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\bin\VS'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\bin'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: false
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'