name: 2.1.$(devops_buildNumber)

pr:
  branches:
    include:
    - master
    - dev
    - v3.x

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format(''), 1500)]

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: OneLocBuild@2
  enabled: false
  inputs:
    locProj: 'Build\Localize\LocProject.json'
    outDir: '$(Build.Repository.LocalPath)'
    packageSourceAuth: 'patAuth'
    patVariable: '$(ONELOCBUILD)'
    continueOnError: true
- task: CopyFiles@2
  enabled: false
  displayName: 'Copy Loc files to publish directories'
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)/loc
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  enabled: false
  displayName: 'Publish Artifact: loc'
  inputs:
    ArtifactName: 'loc'
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.\Build'
  
- task: Gulp@1
  inputs:
    buildNumber: $(devops_buildNumber)
    gulpFile: '.\Build\gulpfile.js'
    targets: 'build-all'
    enableCodeCoverage: false
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      function GenerateIndexJson($ctx, $bundleVersion, $fileName, $rootPath)
      {
      $filePath = Join-Path -Path $rootPath -ChildPath $fileName
      
      $json = @"   
          {
              "version": "$BundleV1Template",
              "commitId" : "$(Build.SourceVersion)"
          }
      "@
      
          $json | Out-File -FilePath $filePath -Encoding ascii
          $blobName = "ExtensionBundleTemplates\versions\" + $fileName
          Set-AzureStorageBlobContent -Container "public" -File $filePath -Blob $blobName -Context $ctx -Force
      }
      
      # get the build version
      $BundleV1Template = "1.0." + $env:devops_buildNumber
      $BundleV2Template = "2.0." + $env:devops_buildNumber
      $BundleV3Template = "3.0." + $env:devops_buildNumber
      
      $rootPath = $pwd
      
      # Storage Context
      $ctx = New-AzureStorageContext -StorageAccountName "$(ACCOUNT_NAME)" -SasToken "$(ACCOUNT_KEY)"
      
      $fileName = "ExtensionBundle.v1.LastestVersion.json" 
      GenerateIndexJson $ctx $BundleV1Template $fileName $rootPath
      
      $fileName = "ExtensionBundle.v2.LastestVersion.json" 
      GenerateIndexJson $ctx $BundleV1Template $fileName $rootPath
      
      $fileName = "ExtensionBundle.v3.LastestVersion.json" 
      GenerateIndexJson $ctx $BundleV1Template $fileName $rootPath

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\bin\VS'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\bin'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: false
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'